apiVersion: apps/v1
kind: Deployment
metadata:
  name: term
  labels:
    app: term
spec:
  replicas: 1
  selector:
    matchLabels:
      app: term
  template:
    metadata:
      labels:
        app: term
    spec:
      containers:
        - name: term
          image: "username/term:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
